using System;
using System.Collections.Generic;
using System.Text;
using FMS.Domain.Entities;

namespace FMS.Infrastructure.SeedData
{
    public static partial class ProdSeedData
    {
        public static County[] GetCounties()
        {
            var counties = new List<County> {
                new County { Id = 131, Name = "Appling" },
                new County { Id = 122, Name = "Atkinson" },
                new County { Id = 110, Name = "Bacon" },
                new County { Id = 105, Name = "Baker" },
                new County { Id = 213, Name = "Baldwin" },
                new County { Id = 179, Name = "Banks" },
                new County { Id = 217, Name = "Barrow" },
                new County { Id = 249, Name = "Bartow" },
                new County { Id = 211, Name = "Ben Hill" },
                new County { Id = 194, Name = "Berrien" },
                new County { Id = 259, Name = "Bibb" },
                new County { Id = 145, Name = "Bleckley" },
                new County { Id = 108, Name = "Brantley" },
                new County { Id = 158, Name = "Brooks" },
                new County { Id = 111, Name = "Bryan" },
                new County { Id = 159, Name = "Bulloch" },
                new County { Id = 203, Name = "Burke" },
                new County { Id = 188, Name = "Butts" },
                new County { Id = 112, Name = "Calhoun" },
                new County { Id = 169, Name = "Camden" },
                new County { Id = 113, Name = "Candler" },
                new County { Id = 241, Name = "Carroll" },
                new County { Id = 225, Name = "Catoosa" },
                new County { Id = 114, Name = "Charlton" },
                new County { Id = 242, Name = "Chatham" },
                new County { Id = 137, Name = "Chattahoochee" },
                new County { Id = 174, Name = "Chattooga" },
                new County { Id = 243, Name = "Cherokee" },
                new County { Id = 252, Name = "Clarke" },
                new County { Id = 104, Name = "Clay" },
                new County { Id = 204, Name = "Clayton" },
                new County { Id = 178, Name = "Clinch" },
                new County { Id = 245, Name = "Cobb" },
                new County { Id = 146, Name = "Coffee" },
                new County { Id = 227, Name = "Colquitt" },
                new County { Id = 232, Name = "Columbia" },
                new County { Id = 212, Name = "Cook" },
                new County { Id = 250, Name = "Coweta" },
                new County { Id = 115, Name = "Crawford" },
                new County { Id = 220, Name = "Crisp" },
                new County { Id = 170, Name = "Dade" },
                new County { Id = 180, Name = "Dawson" },
                new County { Id = 244, Name = "Decatur" },
                new County { Id = 218, Name = "DeKalb" },
                new County { Id = 175, Name = "Dodge" },
                new County { Id = 189, Name = "Dooly" },
                new County { Id = 257, Name = "Dougherty" },
                new County { Id = 253, Name = "Douglas" },
                new County { Id = 195, Name = "Early" },
                new County { Id = 103, Name = "Echols" },
                new County { Id = 123, Name = "Effingham" },
                new County { Id = 200, Name = "Elbert" },
                new County { Id = 198, Name = "Emanuel" },
                new County { Id = 109, Name = "Evans" },
                new County { Id = 176, Name = "Fannin" },
                new County { Id = 235, Name = "Fayette" },
                new County { Id = 246, Name = "Floyd" },
                new County { Id = 238, Name = "Forsyth" },
                new County { Id = 201, Name = "Franklin" },
                new County { Id = 261, Name = "Fulton" },
                new County { Id = 165, Name = "Gilmer" },
                new County { Id = 124, Name = "Glascock" },
                new County { Id = 216, Name = "Glynn" },
                new County { Id = 230, Name = "Gordon" },
                new County { Id = 208, Name = "Grady" },
                new County { Id = 171, Name = "Greene" },
                new County { Id = 226, Name = "Gwinnett" },
                new County { Id = 214, Name = "Habersham" },
                new County { Id = 256, Name = "Hall" },
                new County { Id = 107, Name = "Hancock" },
                new County { Id = 209, Name = "Haralson" },
                new County { Id = 138, Name = "Harris" },
                new County { Id = 190, Name = "Hart" },
                new County { Id = 152, Name = "Heard" },
                new County { Id = 248, Name = "Henry" },
                new County { Id = 239, Name = "Houston" },
                new County { Id = 139, Name = "Irwin" },
                new County { Id = 222, Name = "Jackson" },
                new County { Id = 147, Name = "Jasper" },
                new County { Id = 160, Name = "Jeff Davis" },
                new County { Id = 199, Name = "Jefferson" },
                new County { Id = 153, Name = "Jenkins" },
                new County { Id = 140, Name = "Johnson" },
                new County { Id = 161, Name = "Jones" },
                new County { Id = 181, Name = "Lamar" },
                new County { Id = 141, Name = "Lanier" },
                new County { Id = 223, Name = "Laurens" },
                new County { Id = 172, Name = "Lee" },
                new County { Id = 148, Name = "Liberty" },
                new County { Id = 125, Name = "Lincoln" },
                new County { Id = 102, Name = "Long" },
                new County { Id = 254, Name = "Lowndes" },
                new County { Id = 192, Name = "Lumpkin" },
                new County { Id = 182, Name = "Macon" },
                new County { Id = 166, Name = "Madison" },
                new County { Id = 133, Name = "Marion" },
                new County { Id = 210, Name = "McDuffie" },
                new County { Id = 126, Name = "McIntosh" },
                new County { Id = 196, Name = "Meriwether" },
                new County { Id = 154, Name = "Miller" },
                new County { Id = 215, Name = "Mitchell" },
                new County { Id = 184, Name = "Monroe" },
                new County { Id = 134, Name = "Montgomery" },
                new County { Id = 197, Name = "Morgan" },
                new County { Id = 205, Name = "Murray" },
                new County { Id = 258, Name = "Muscogee" },
                new County { Id = 231, Name = "Newton" },
                new County { Id = 191, Name = "Oconee" },
                new County { Id = 127, Name = "Oglethorpe" },
                new County { Id = 219, Name = "Paulding" },
                new County { Id = 221, Name = "Peach" },
                new County { Id = 185, Name = "Pickens" },
                new County { Id = 116, Name = "Pierce" },
                new County { Id = 149, Name = "Pike" },
                new County { Id = 233, Name = "Polk" },
                new County { Id = 155, Name = "Pulaski" },
                new County { Id = 183, Name = "Putnam" },
                new County { Id = 100, Name = "Quitman" },
                new County { Id = 167, Name = "Rabun" },
                new County { Id = 156, Name = "Randolph" },
                new County { Id = 260, Name = "Richmond" },
                new County { Id = 251, Name = "Rockdale" },
                new County { Id = 135, Name = "Schley" },
                new County { Id = 157, Name = "Screven" },
                new County { Id = 150, Name = "Seminole" },
                new County { Id = 240, Name = "Spalding" },
                new County { Id = 229, Name = "Stephens" },
                new County { Id = 117, Name = "Stewart" },
                new County { Id = 236, Name = "Sumter" },
                new County { Id = 128, Name = "Talbot" },
                new County { Id = 118, Name = "Taliaferro" },
                new County { Id = 136, Name = "Tattnall" },
                new County { Id = 142, Name = "Taylor" },
                new County { Id = 164, Name = "Telfair" },
                new County { Id = 173, Name = "Terrell" },
                new County { Id = 234, Name = "Thomas" },
                new County { Id = 237, Name = "Tift" },
                new County { Id = 151, Name = "Toombs" },
                new County { Id = 129, Name = "Towns" },
                new County { Id = 101, Name = "Treutlen" },
                new County { Id = 247, Name = "Troup" },
                new County { Id = 186, Name = "Turner" },
                new County { Id = 130, Name = "Twiggs" },
                new County { Id = 168, Name = "Union" },
                new County { Id = 202, Name = "Upson" },
                new County { Id = 224, Name = "Walker" },
                new County { Id = 228, Name = "Walton" },
                new County { Id = 177, Name = "Ware" },
                new County { Id = 162, Name = "Warren" },
                new County { Id = 206, Name = "Washington" },
                new County { Id = 143, Name = "Wayne" },
                new County { Id = 120, Name = "Webster" },
                new County { Id = 106, Name = "Wheeler" },
                new County { Id = 193, Name = "White" },
                new County { Id = 255, Name = "Whitfield" },
                new County { Id = 144, Name = "Wilcox" },
                new County { Id = 163, Name = "Wilkes" },
                new County { Id = 207, Name = "Wilkinson" },
                new County { Id = 187, Name = "Worth" },
                new County { Id = 99, Name = "OUT OF STATE" }
            };

            return counties.ToArray();
        }
    }
}
