name: .NET Unit Tests

on:
  pull_request:

jobs:
  dotnet-test:
    # ↓ Change this to "false" to disable the workflow without any alert messages.
    if: ${{ true }}
    # ↑ Change to "true" (or delete) to enable the workflow.
    
    name: Run unit tests
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
